apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Cloudlab
  region: ap-southeast-1
  # version: "1.17"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

vpc:
  clusterEndpoints:
    publicAccess: false # True if you want to enable
    privateAccess: true
  subnets:
    private:
      eu-west-1a: { id: subnet-03b817aa79a015507 }
      eu-west-1b: { id: subnet-099fb0be9b96334d7 }

managedNodeGroups:
  - name: node-group-01
    labels: { role: workers }
    instanceType: t3.medium
    privateNetworking: true
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 50
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/.ssh/eks.pub # will use ~/.ssh/id_rsa.pub as the default ssh key