apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Cloudlab
  region: ap-southeast-1
  # version: 1.18
  
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

nodeGroups:
  - name: node-group-01
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 50
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub # will use ~/.ssh/id_rsa.pub as the default ssh key
