apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Cloudlab
  region: ap-southeast-1
  # version: 1.18

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
  
nodeGroups:
  - name: node-group-01
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 50
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub # will use ~/.ssh/id_rsa.pub as the default ssh key


fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system
  - name: fp-dev
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: dev
        labels:
          env: dev
          checks: passed

##After installation

# $ kubectl create namespace dev
# namespace/dev created

# $ kubectl run nginx --image=nginx --restart=Never --namespace dev
# pod/nginx created

# $ kubectl get pods --all-namespaces --output wide






